### ISSUE TITLE
df.attrs contains only data_path

### ISSUE THREAD

**Issue by Qubitol** [mhostert/DarkNews-generator#28]
This code
```python
gen_object = GenLauncher(mzprime=1.25, m4=0.140, neval=1000, noHF=True, HNLtype="dirac", loglevel="INFO")
df_1 = gen_object.run()
```
creates the dataframe `df_1`.
If I inspect `df_1.attrs`, it contains only:
```python
{'data_path': PosixPath('data/miniboone_fhc/3plus1/m4_0.14_mzprime_1.25_dirac')}
```

**Comment by mhostert** [comment]
Fixed -- not sure what the problem was, in my version it always contained both detector and model classes inside attrs?

Can you confirm this is a problem on your end? I'll put a test entry for that.

**Comment by mhostert** [comment]
The standard behavior for older versions of pandas was to drop df.attrs when concatenating two pandas dataframes. Now we check if this happens, and if it does, we add it back in manually.
