### ISSUE TITLE
np.float128

### ISSUE THREAD

**Issue by austinschneider** [mhostert/DarkNews-generator#33]
The numpy.float128 alias is not available on all platforms:
https://numpy.org/doc/stable/reference/arrays.scalars.html#numpy.float128

If just need high-precision and do not need a specific alignment, it would make sense to change `np.float128` to `np.longdouble` on this line:

https://github.com/mhostert/DarkNews-generator/blob/a7d90b83afba6fff1843f88c1e3aaea43ebb140e/src/DarkNews/model.py#L493

**Comment by mhostert** [comment]
Thanks, the issue was solved with your pull request.
